name: Deploy

on:
  push:
    branches:
      - main

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the PR head
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Chromatic publish
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          token: ${{ secrets.GITHUB_TOKEN }}
