name: Prettier Check

on:
  pull_request:
    branches:
      - main
      - '**' # Run on all branches for pull requests

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*' # Use the latest LTS version of Node.js

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier check
        run: npm run prettier:check
