name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      #👇 Adds Chromatic as a step in the workflow
      - id: 'chromatic'
        uses: chromaui/action@latest
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken,
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # Only publish, no tests
          exitOnceUploaded: true
          token: ${{ secrets.GITHUB_TOKEN }}

